
// Automatically generated by xmlvm2obj. Do not edit!


#import "crossmobile_rt_StrongReference.h"

@implementation crossmobile_rt_StrongReference;

- (void) dealloc
{
    [refValue release];
    [super dealloc];
}

- (instancetype) __init_crossmobile_rt_StrongReference__
{
    return [self init];
}

- (instancetype) __init_crossmobile_rt_StrongReference___java_lang_Object :(java_lang_Object*)n1
{
    [self set___java_lang_Object:n1];
    return self;
}

- (java_lang_Object*) get__
{
    return [XMLVM_NIL2NULL(refValue) retain];
}

- (void) set___java_lang_Object :(java_lang_Object*)n1
{
    [self->refValue release];
    self->refValue = [XMLVM_NULL2NIL(n1) retain];
}

@end

