/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_crossmobile_NativeHandler */

#ifndef _Included_org_crossmobile_NativeHandler
#define _Included_org_crossmobile_NativeHandler
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     org_crossmobile_NativeHandler
	* Method:    handlerToPid
	* Signature: (J)J
	*/
	JNIEXPORT jlong JNICALL Java_org_crossmobile_NativeHandler_handlerToPid
	(JNIEnv *, jclass, jlong);

/*
 * Class:     org_crossmobile_NativeHandler
 * Method:    kill
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_NativeHandler_kill
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
