/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_crossmobile_backend_avian_SkPath */

#ifndef _Included_org_crossmobile_backend_avian_SkPath
#define _Included_org_crossmobile_backend_avian_SkPath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_crossmobile_backend_avian_SkPath
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_crossmobile_backend_avian_SkPath_init
  (JNIEnv *, jclass);

/*
 * Class:     org_crossmobile_backend_avian_SkPath
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkPath_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_crossmobile_backend_avian_SkPath
 * Method:    moveTo
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkPath_moveTo
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     org_crossmobile_backend_avian_SkPath
 * Method:    quadTo
 * Signature: (JDDDD)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkPath_quadTo
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_crossmobile_backend_avian_SkPath
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkPath_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_crossmobile_backend_avian_SkPath
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkPath_reset
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
