/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_crossmobile_backend_avian_SkBitmap */

#ifndef _Included_org_crossmobile_backend_avian_SkBitmap
#define _Included_org_crossmobile_backend_avian_SkBitmap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_crossmobile_backend_avian_SkBitmap
 * Method:    initFromFileName
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_crossmobile_backend_avian_SkBitmap_initFromFileName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_crossmobile_backend_avian_SkBitmap
 * Method:    initFromBlob
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_crossmobile_backend_avian_SkBitmap_initFromBlob
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_crossmobile_backend_avian_SkBitmap
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkBitmap_destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
