/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_crossmobile_backend_aroma_AromaGraphicsBridge */

#ifndef _Included_org_crossmobile_backend_aroma_AromaGraphicsBridge
#define _Included_org_crossmobile_backend_aroma_AromaGraphicsBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_crossmobile_backend_aroma_AromaGraphicsBridge
 * Method:    initSDL
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_crossmobile_backend_aroma_AromaGraphicsBridge_initSDL
  (JNIEnv *, jclass);

/*
 * Class:     org_crossmobile_backend_aroma_AromaGraphicsBridge
 * Method:    quitSDL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_aroma_AromaGraphicsBridge_quitSDL
  (JNIEnv *, jclass);

/*
 * Class:     org_crossmobile_backend_aroma_AromaGraphicsBridge
 * Method:    pollSDLEvents
 * Signature: ()Lorg/crossmobile/backend/aroma/event/AromaEvent;
 */
JNIEXPORT jobject JNICALL Java_org_crossmobile_backend_aroma_AromaGraphicsBridge_pollSDLEvents
  (JNIEnv *, jclass);

/*
 * Class:     org_crossmobile_backend_aroma_AromaGraphicsBridge
 * Method:    setDebugLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_aroma_AromaGraphicsBridge_setDebugLevel
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
