/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_crossmobile_backend_avian_SkPaint */

#ifndef _Included_org_crossmobile_backend_avian_SkPaint
#define _Included_org_crossmobile_backend_avian_SkPaint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_crossmobile_backend_avian_SkPaint
 * Method:    initPaint
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_crossmobile_backend_avian_SkPaint_initPaint
  (JNIEnv *, jclass);

/*
 * Class:     org_crossmobile_backend_avian_SkPaint
 * Method:    destroyPaint
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkPaint_destroyPaint
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_crossmobile_backend_avian_SkPaint
 * Method:    setStyle
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkPaint_setStyle
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     org_crossmobile_backend_avian_SkPaint
 * Method:    setStrokeWidth
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkPaint_setStrokeWidth
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_crossmobile_backend_avian_SkPaint
 * Method:    setColor
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkPaint_setColor
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_crossmobile_backend_avian_SkPaint
 * Method:    setAntialias
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkPaint_setAntialias
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_crossmobile_backend_avian_SkPaint
 * Method:    setAlpha
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkPaint_setAlpha
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_crossmobile_backend_avian_SkPaint
 * Method:    setStrokeJoin
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkPaint_setStrokeJoin
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     org_crossmobile_backend_avian_SkPaint
 * Method:    setStrokeCap
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkPaint_setStrokeCap
  (JNIEnv *, jclass, jlong, jbyte);

#ifdef __cplusplus
}
#endif
#endif
