/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_crossmobile_backend_avian_SkBitmap */

#ifndef _Included_org_crossmobile_backend_avian_SkBitmap
#define _Included_org_crossmobile_backend_avian_SkBitmap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_crossmobile_backend_avian_SkBitmap
 * Method:    initFromSizes
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_crossmobile_backend_avian_SkBitmap_initFromSizes
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_crossmobile_backend_avian_SkBitmap
 * Method:    initFromByteArray
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_crossmobile_backend_avian_SkBitmap_initFromByteArray
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_crossmobile_backend_avian_SkBitmap
 * Method:    initFromBlob
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_crossmobile_backend_avian_SkBitmap_initFromBlob
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_crossmobile_backend_avian_SkBitmap
 * Method:    initFromBitmap
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_crossmobile_backend_avian_SkBitmap_initFromBitmap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_crossmobile_backend_avian_SkBitmap
 * Method:    postInit
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_crossmobile_backend_avian_SkBitmap_postInit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_crossmobile_backend_avian_SkBitmap
 * Method:    getBytesFromImage
 * Signature: (JZD)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_crossmobile_backend_avian_SkBitmap_getBytesFromImage
  (JNIEnv *, jclass, jlong, jboolean, jdouble);

/*
 * Class:     org_crossmobile_backend_avian_SkBitmap
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkBitmap_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_crossmobile_backend_avian_SkBitmap
 * Method:    extractAlpha
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkBitmap_extractAlpha
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_crossmobile_backend_avian_SkBitmap
 * Method:    adjustColor
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkBitmap_adjustColor
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
