/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_crossmobile_backend_avian_SkFont */

#ifndef _Included_org_crossmobile_backend_avian_SkFont
#define _Included_org_crossmobile_backend_avian_SkFont
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_crossmobile_backend_avian_SkFont
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_crossmobile_backend_avian_SkFont_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_crossmobile_backend_avian_SkFont
 * Method:    init
 * Signature: (Ljava/lang/String;D)J
 */
JNIEXPORT jlong JNICALL Java_org_crossmobile_backend_avian_SkFont_init
  (JNIEnv *, jclass, jstring, jdouble);

/*
 * Class:     org_crossmobile_backend_avian_SkFont
 * Method:    postInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_crossmobile_backend_avian_SkFont_postInit
  (JNIEnv *, jobject);

/*
 * Class:     org_crossmobile_backend_avian_SkFont
 * Method:    measureText
 * Signature: (JLjava/lang/String;)Lcrossmobile/ios/coregraphics/CGSize;
 */
JNIEXPORT jobject JNICALL Java_org_crossmobile_backend_avian_SkFont_measureText
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
