/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_crossmobile_backend_avian_SDLEvent */

#ifndef _Included_org_crossmobile_backend_avian_SDLEvent
#define _Included_org_crossmobile_backend_avian_SDLEvent
#ifdef __cplusplus
extern "C" {
#endif
#undef org_crossmobile_backend_avian_SDLEvent_WINDOWEVENT
#define org_crossmobile_backend_avian_SDLEvent_WINDOWEVENT 512L
#undef org_crossmobile_backend_avian_SDLEvent_MOUSEMOTION
#define org_crossmobile_backend_avian_SDLEvent_MOUSEMOTION 1024L
#undef org_crossmobile_backend_avian_SDLEvent_MOUSEBUTTON
#define org_crossmobile_backend_avian_SDLEvent_MOUSEBUTTON 1025L
/*
 * Class:     org_crossmobile_backend_avian_SDLEvent
 * Method:    initSDLEvent
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_crossmobile_backend_avian_SDLEvent_initSDLEvent
  (JNIEnv *, jclass);

/*
 * Class:     org_crossmobile_backend_avian_SDLEvent
 * Method:    pollEvent
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_crossmobile_backend_avian_SDLEvent_pollEvent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_crossmobile_backend_avian_SDLEvent
 * Method:    getType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_crossmobile_backend_avian_SDLEvent_getType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_crossmobile_backend_avian_SDLEvent
 * Method:    getWindowEvent
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_org_crossmobile_backend_avian_SDLEvent_getWindowEvent
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
