package org.crossmobile.xray;

import javax.swing.*;
import java.awt.*;

public class UIKitTouchPanel {
    public JPanel buttonPanel;
    private JPanel base;
    public JList<String> entriesL;
    public JToggleButton touchB;
    private JButton cleanupB;

    public UIKitTouchPanel() {
        $$$setupUI$$$();
        cleanupB.addActionListener(e -> ((DefaultListModel) entriesL.getModel()).removeAllElements());
    }

    private void createUIComponents() {
        touchB = new ToggleButton("/icons/touch.png");
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        base = new JPanel();
        base.setLayout(new BorderLayout(0, 0));
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
        base.add(buttonPanel, BorderLayout.NORTH);
        touchB.setSelected(false);
        buttonPanel.add(touchB);
        cleanupB = new JButton();
        cleanupB.setIcon(new ImageIcon(getClass().getResource("/icons/sweep.png")));
        cleanupB.setText("");
        buttonPanel.add(cleanupB);
        final JScrollPane scrollPane1 = new JScrollPane();
        base.add(scrollPane1, BorderLayout.CENTER);
        entriesL = new JList();
        scrollPane1.setViewportView(entriesL);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return base;
    }
}
